"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import Sidebar from "@/compoenents/sidebar/sidebar";
import Header from "@/compoenents/Header/Navpanel";
import { Menu } from "lucide-react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{

    const [open, setOpen] = useState(false);
  const [collapsed, setCollapsed] = useState(false);
  
  const user = {
    name: "Shivam Dubey",
    email: "shivam.dubey@gmail.com",
    image: "/logo.png",
  };
  return (
     <html lang="en">
      <body className="bg-white"> 
        <div className="flex min-h-screen bg-white"> 


          <Sidebar user={user} open={open} setOpen={setOpen} collapsed={collapsed} setCollapsed={setCollapsed} />

          <div className="flex-1 flex flex-col min-w-0 bg-white">
            

            <div className="flex items-center p-4 border-b md:hidden bg-white sticky top-0 z-30">
              <button 
                onClick={() => setOpen(true)}
                className="p-2 -ml-2 hover:bg-gray-100 rounded-lg transition-colors"
                aria-label="Open Menu"
              >
                <Menu size={15} className="text-black" />
              </button>
              <div className="ml-4 font-bold text-black text-lg"></div>
            </div>
   
            <Header name={user.name}/>
            

            <main className="flex-1 bg-gray-50/50 overflow-x-hidden">
              <div className="p-4 md:p-6 lg:p-8">
                {children}
              </div>
            </main>
          </div>

        </div>
      </body>
    </html>
  );
}
